name: AWS Continuous Deployment

on:
  push:
    branches:
      - actions_cd
  pull_request:
    branches:
      - actions_cd

run-name: "Continuous Deployment (@${{ github.actor }})"

jobs:
  test_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Test CD
        run: echo "Test of Continuous Deployment"

