name: AWS CI/CD

on:
  push:
    branches:
      - actions_cd

jobs:
  actions_test:
    runs-on: ubuntu-latest
    steps:
      - name: Test GitHub Actions
        run: echo "Test of GitHub Actions"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.11"
#       - name: Set up Node
#         uses: actions/setup-node@v3
#         with: 
#           node-version: "16"
#       - name: Install Python dependencies and CDK
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements
#           npm install -g aws-cdk
#       - name: Deploy to AWS
#           run: cdk deploy --app="python3 ${PWD}/app.py" --require-approval=never
#       - name: Destroy stack
#           run: cdk destroy --app="python3 ${PWD}/app.py" --force
