# Manually deploy the CDK Stack defined by the main branch of the repo

name: AWS Manual CDK Deploy

on:
  push:  # temporary. final version should only run on workflow dispatch
    branches:
      - actions_cd
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up Node
        uses: actions/setup-node@v3
        with: 
          node-version: "16"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
      # using an AWS access key stored in GitHub secrets
      # given more time, using GitHub OIDC and AWS identity provider would be better
      - name: Deploy CDK Stack
        run: cdk deploy PointlessAnalogiesStack --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          